- dir_docs: !!python/unicode '/home/gpoole/my_code/gbpBuild/docs'
- dir_docs_api_src: !!python/unicode '/home/gpoole/my_code/gbpBuild/docs/src'
- dir_docs_build: !!python/unicode '/home/gpoole/my_code/gbpBuild/docs/_build'
- dir_python: !!python/unicode '/home/gpoole/my_code/gbpBuild/python'
- python_packages:
  - !!python/unicode 'gbpBuild'
- is_C_project: false
- is_Python_project: true
- version: 0.2.1
- release: 0.2.1
