- dir_docs: /Users/gpoole/my_code/gbpBuild/docs
- dir_docs_api_src: /Users/gpoole/my_code/gbpBuild/docs/src
- dir_docs_build: /Users/gpoole/my_code/gbpBuild/docs/_build
- dir_python: /Users/gpoole/my_code/gbpBuild/python
- python_packages:
  - gbpBuild
- is_C_project: false
- is_Python_project: true
- version: 0.2.1
- release: 0.2.1
