- name: gbpPy
- author: Gregory B. Poole
- author_email: gbpoole@gmail.com
- description: One line description of project.
- dir_python: python
- dir_python_bin: python/bin
- dir_docs: docs
- dir_docs_build: docs/build
- dir_docs_api_src: docs/api
- dir_python_pkg: python/gbpPy/gbpPy
- is_C_project: false
- is_Python_project: true
