#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# gbpPy documentation build configuration file
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute

import os
import shutil
import sys
from datetime import datetime

from recommonmark.parser import CommonMarkParser

class project:
    def __init__(self,project_name,dir_root,dir_docs_build):
        self.name = project_name

        self.author = "author"
        self.description = "One line description of project here."

        # Set some project direcories
        self.dir_root    = dir_root
        self.dir_docs    = os.path.join(self.dir_root,"docs")
        self.dir_python  = os.path.join(self.dir_root,"python")

        # Infer the name of the project from the root

        # Check if this is a C-project (CMakeList.txt will exist if so)
        if(os.path.isfile(os.path.join(self.dir_root,"CMakeLists.txt"))):
            self.is_C_project = True
        else:
            self.is_C_project = False

        # Check if this is a Python-project (the python directory will exist if so)
        if(os.path.isdir(self.dir_python)):
            self.is_Python_project = True
        else:
            self.is_Python_project = False

        # If dir_docs_build is of the format "@...@" then it is *not*
        # being called from cmake ... so assume we are doing a python
        # build.  Otherwise, cmake has performed a variable substitution
        # (see support/cmake/FindSphinx.cmake) and we just use that.
        if(dir_docs_build!=dir_docs_build.strip('@')):
            # Verify that this is a python build
            if(self.is_Python_project):
                self.dir_docs_build = os.path.join(self.dir_root,"python/build/sphinx")
            else:
                raise("Could not set python docs build directory.")
        else:
            self.dir_docs_build = dir_docs_build

        # Extract version & release from .version file.
        try:
            with open("%s/.version"%(self.dir_root),"r") as fp_in:
                self.version = str(fp_in.readline())
        except:
            print("Project '.version' file not found.  Setting version='unset'")
            self.version='unset'
        self.release = self.version

# Set the project root directory
project_root_dir = os.path.abspath(os.path.normpath(os.path.join(os.path.dirname(__file__),'../')))

# Add gbpBuild python code to path and import it
sys.path.append(os.path.abspath(os.path.join(project_root_dir,"extern/gbpBuild/python/")))

# Add project python directory so that autodoc can find it
sys.path.append(os.path.abspath(os.path.join(project_root_dir,"python")))
sys.path.append(os.path.abspath(os.path.join(project_root_dir,"python/bin")))

# Parse the project directory to learn what we need about the project
gbpBuild_project = project("gbpPy",project_root_dir,"@Sphinx_BUILD_DIR@")

# Make sure the build directory exists
if(not os.path.isdir(gbpBuild_project.dir_docs_build)):
    os.makedirs(gbpBuild_project.dir_docs_build)

# Copy project .rst files to build directory
filenames = os.listdir(os.path.abspath(os.path.join(project_root_dir,"docs")))
for filename in filenames:
    if filename.endswith(".rst"):
        shutil.copy2(os.path.abspath(os.path.join(project_root_dir,"docs",filename)),os.path.join(gbpBuild_project.dir_docs_build,filename)) 

# Add it to the project path
breathe_directory = "%s/breathe/"%(gbpBuild_project.dir_docs_build)
sys.path.append( breathe_directory )

# -- General configuration ------------------------------------------------

# Set minimal Sphinx version
needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'breathe']

# Some things that Breathe needs
breathe_projects        = { gbpBuild_project.name: "%s/doxygen/xml/"%(gbpBuild_project.dir_docs_build) }
breathe_default_project =   gbpBuild_project.name

# Add any paths that contain templates here, relative to this directory.
templates_path = ['%s/templates'%(gbpBuild_project.dir_docs)]

# Add a markdown parser
source_parsers = {
    '.md': CommonMarkParser,
}

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = 'index'

# General information about the gbpBuild_project.
project = gbpBuild_project.name
year = datetime.today().year
copyright = str(year)+', %s'%(gbpBuild_project.author)
author = gbpBuild_project.author

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.

# Extract version from .version file.
# n.b.: 'version' should be the short X.Y version
#       'release' should be the full version, including alpha/beta/rc tags
version = gbpBuild_project.version
release = gbpBuild_project.release

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['build-*','**/extern']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme_path =['%s/themes'%(gbpBuild_project.dir_docs)]
html_theme = 'gbp_theme'
html_show_sourcelink = False
html_favicon = '%s/static/favicon.ico'%(gbpBuild_project.dir_docs)
html_logo = '%s/static/logo.gif'%(gbpBuild_project.dir_docs)

html_sidebars = { '**': ['globaltoc.html', 'relations.html', 'sourcelink.html', 'searchbox.html'], }

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {'gbp_project_name':gbpBuild_project.name}

extra_nav_links = {'Index' : 'genindex.html'}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['%s/static'%(gbpBuild_project.dir_docs)]

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = '%sdoc'%(gbpBuild_project.dir_docs)

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, '%s.tex'%(gbpBuild_project.name), '%s Documentation'%(gbpBuild_project.name),
     gbpBuild_project.author, 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, gbpBuild_project.name.lower(), '%s Documentation'%(gbpBuild_project.name),
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, gbpBuild_project.name, '%s Documentation'%(gbpBuild_project.name),
     author, gbpBuild_project.name, gbpBuild_project.description,
     'Miscellaneous'),
]
